export const ADD_COMPONENT = 'ADD_COMPONENT';
export const DELETE_COMPONENT = 'DELETE_COMPONENT';
export const EDIT_COMPONENT = 'EDIT_COMPONENT';
export const ADD_RECIPE = 'ADD_RECIPE';
export const DELETE_RECIPE = 'DELETE_RECIPE';
export const EDIT_RECIPE = 'EDIT_RECIPE';
export const ADD_COM_TO_RECIPE = 'ADD_COM_TO_RECIPE';
export const EDIT_BOOLEAN = 'EDIT_BOOLEAN';
